# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4db912f7c53ecbe361c3ba329d883504ea434438c92a4bdc664e22bdaa6a34c511c7cf605e3ad1cead6cfcb38d738ad4da792e5948d4aa904978fc1e0cde817f

test:
  secret_key_base: 5b7c3450db6faa6781ffb2a423dadf3f59b4f55b3e8e4e18c96082cf82b403a208bcb62960581404dfeaecf11ae920d5f591a49fcf6352c0a5b6acd2254e85cb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
